services:
  - type: web
    name: sunways-proxy
    env: python
    # This command tells Render to install the libraries from your requirements.txt file
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
